Return an empty string if the emojis are not supported
IonicaBizau/emojic pull request #13
Opened 2017-05-08 13:24 UTC by Khaledgarbaya

Emojis are not supported in windows terminals instead you will see weird characters, this PR adds a check if the platform does not support emojis we return an empty string

2017-05-08 13:30 UTC, IonicaBizau requested changes
Let's support Linux too. Thanks! :+1:

2017-05-08 13:30 UTC, IonicaBizau commented on lib/index.js
> +    if (!process.stdout.isTTY || !process.platform === 'darwin')
Let's support Linux too. They are not colorful, but they are still cute enough. :grin: 

Also, do we really need `process.stdout.isTTY` here? I don't see any problem piping emojis into files.

2017-05-08 13:45 UTC, Khaledgarbaya commented
@IonicaBizau done, we return empty string only on windows

2017-05-12 10:13 UTC, IonicaBizau approved these changes

2017-05-12 10:13 UTC, merged